apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  namespace: hackathon
spec:
  selector:
    app: blockchain-service-provider
    tier: backend
  ports:
  - protocol: TCP
    port: 8093
    targetPort: 8093

